services:
  app:
    image: guangfu250923:latest
    container_name: guangfu250923
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
      - PORT=8080
    env_file:
      - .env
    network_mode: bridge
